#pragma once
// <auto-generated />

#include <cstdint>

namespace Crowny
{
    using MouseCode = uint32_t;

    namespace Mouse
    {
        enum : MouseCode
        {
            Button0 = 0,
            Button1 = 1,
            Button2 = 2,
            Button3 = 3,
            Button4 = 4,
            Button5 = 5,
            Button6 = 6,
            Button7 = 7,
            ButtonLast = 7,
            ButtonLeft = 0,
            ButtonRight = 1,
            ButtonMiddle = 2,
        };
    } // namespace Mouse
} // namespace Crowny
