#pragma once

#define DEFAULT_ASSET_FILE_PADDING 12.0f
#define DEFAULT_ASSET_THUMBNAIL_SIZE 48.0f

#define MIN_ASSET_THUMBNAIL_SIZE 32.0f
#define MAX_ASSET_THUMBNAIL_SIZE 128.0f

#define DRAG_SENSITIVITY 0.01f