# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_win64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_win64)
  glfw_config = debug_win64
  glad_config = debug_win64
  freetype_gl_config = debug_win64
  imgui_config = debug_win64
  freetype2_config = debug_win64
  assimp_config = debug_win64
  Crowny_config = debug_win64
  Crowny_Editor_config = debug_win64
  Crowny_Sharp_config = debug_win64
  Crowny_Sandbox_config = debug_win64

else ifeq ($(config),debug_linux64)
  glfw_config = debug_linux64
  glad_config = debug_linux64
  freetype_gl_config = debug_linux64
  imgui_config = debug_linux64
  freetype2_config = debug_linux64
  assimp_config = debug_linux64
  Crowny_config = debug_linux64
  Crowny_Editor_config = debug_linux64
  Crowny_Sharp_config = debug_linux64
  Crowny_Sandbox_config = debug_linux64

else ifeq ($(config),debug_macos64)
  glfw_config = debug_macos64
  glad_config = debug_macos64
  freetype_gl_config = debug_macos64
  imgui_config = debug_macos64
  freetype2_config = debug_macos64
  assimp_config = debug_macos64
  Crowny_config = debug_macos64
  Crowny_Editor_config = debug_macos64
  Crowny_Sharp_config = debug_macos64
  Crowny_Sandbox_config = debug_macos64

else ifeq ($(config),debug_web)
  glfw_config = debug_web
  glad_config = debug_web
  freetype_gl_config = debug_web
  imgui_config = debug_web
  freetype2_config = debug_web
  assimp_config = debug_web
  Crowny_config = debug_web
  Crowny_Editor_config = debug_web
  Crowny_Sharp_config = debug_web
  Crowny_Sandbox_config = debug_web

else ifeq ($(config),release_win64)
  glfw_config = release_win64
  glad_config = release_win64
  freetype_gl_config = release_win64
  imgui_config = release_win64
  freetype2_config = release_win64
  assimp_config = release_win64
  Crowny_config = release_win64
  Crowny_Editor_config = release_win64
  Crowny_Sharp_config = release_win64
  Crowny_Sandbox_config = release_win64

else ifeq ($(config),release_linux64)
  glfw_config = release_linux64
  glad_config = release_linux64
  freetype_gl_config = release_linux64
  imgui_config = release_linux64
  freetype2_config = release_linux64
  assimp_config = release_linux64
  Crowny_config = release_linux64
  Crowny_Editor_config = release_linux64
  Crowny_Sharp_config = release_linux64
  Crowny_Sandbox_config = release_linux64

else ifeq ($(config),release_macos64)
  glfw_config = release_macos64
  glad_config = release_macos64
  freetype_gl_config = release_macos64
  imgui_config = release_macos64
  freetype2_config = release_macos64
  assimp_config = release_macos64
  Crowny_config = release_macos64
  Crowny_Editor_config = release_macos64
  Crowny_Sharp_config = release_macos64
  Crowny_Sandbox_config = release_macos64

else ifeq ($(config),release_web)
  glfw_config = release_web
  glad_config = release_web
  freetype_gl_config = release_web
  imgui_config = release_web
  freetype2_config = release_web
  assimp_config = release_web
  Crowny_config = release_web
  Crowny_Editor_config = release_web
  Crowny_Sharp_config = release_web
  Crowny_Sandbox_config = release_web

else ifeq ($(config),dist_win64)
  glfw_config = dist_win64
  glad_config = dist_win64
  freetype_gl_config = dist_win64
  imgui_config = dist_win64
  freetype2_config = dist_win64
  assimp_config = dist_win64
  Crowny_config = dist_win64
  Crowny_Editor_config = dist_win64
  Crowny_Sharp_config = dist_win64
  Crowny_Sandbox_config = dist_win64

else ifeq ($(config),dist_linux64)
  glfw_config = dist_linux64
  glad_config = dist_linux64
  freetype_gl_config = dist_linux64
  imgui_config = dist_linux64
  freetype2_config = dist_linux64
  assimp_config = dist_linux64
  Crowny_config = dist_linux64
  Crowny_Editor_config = dist_linux64
  Crowny_Sharp_config = dist_linux64
  Crowny_Sandbox_config = dist_linux64

else ifeq ($(config),dist_macos64)
  glfw_config = dist_macos64
  glad_config = dist_macos64
  freetype_gl_config = dist_macos64
  imgui_config = dist_macos64
  freetype2_config = dist_macos64
  assimp_config = dist_macos64
  Crowny_config = dist_macos64
  Crowny_Editor_config = dist_macos64
  Crowny_Sharp_config = dist_macos64
  Crowny_Sandbox_config = dist_macos64

else ifeq ($(config),dist_web)
  glfw_config = dist_web
  glad_config = dist_web
  freetype_gl_config = dist_web
  imgui_config = dist_web
  freetype2_config = dist_web
  assimp_config = dist_web
  Crowny_config = dist_web
  Crowny_Editor_config = dist_web
  Crowny_Sharp_config = dist_web
  Crowny_Sandbox_config = dist_web

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := glfw glad freetype-gl imgui freetype2 assimp Crowny Crowny-Editor Crowny-Sharp Crowny-Sandbox

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: assimp freetype-gl freetype2 glad glfw imgui

glfw:
ifneq (,$(glfw_config))
	@echo "==== Building glfw ($(glfw_config)) ===="
	@${MAKE} --no-print-directory -C Crowny/Dependencies/glfw -f Makefile config=$(glfw_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C Crowny/Dependencies/glad -f Makefile config=$(glad_config)
endif

freetype-gl:
ifneq (,$(freetype_gl_config))
	@echo "==== Building freetype-gl ($(freetype_gl_config)) ===="
	@${MAKE} --no-print-directory -C Crowny/Dependencies/freetype-gl -f Makefile config=$(freetype_gl_config)
endif

imgui:
ifneq (,$(imgui_config))
	@echo "==== Building imgui ($(imgui_config)) ===="
	@${MAKE} --no-print-directory -C Crowny/Dependencies/imgui -f Makefile config=$(imgui_config)
endif

freetype2:
ifneq (,$(freetype2_config))
	@echo "==== Building freetype2 ($(freetype2_config)) ===="
	@${MAKE} --no-print-directory -C Crowny/Dependencies/freetype2 -f Makefile config=$(freetype2_config)
endif

assimp:
ifneq (,$(assimp_config))
	@echo "==== Building assimp ($(assimp_config)) ===="
	@${MAKE} --no-print-directory -C Crowny/Dependencies/assimp -f Makefile config=$(assimp_config)
endif

Crowny: imgui freetype-gl assimp freetype2 glfw glad
ifneq (,$(Crowny_config))
	@echo "==== Building Crowny ($(Crowny_config)) ===="
	@${MAKE} --no-print-directory -C Crowny -f Makefile config=$(Crowny_config)
endif

Crowny-Editor: Crowny imgui freetype-gl assimp freetype2 glfw glad
ifneq (,$(Crowny_Editor_config))
	@echo "==== Building Crowny-Editor ($(Crowny_Editor_config)) ===="
	@${MAKE} --no-print-directory -C Crowny-Editor -f Makefile config=$(Crowny_Editor_config)
endif

Crowny-Sharp:
ifneq (,$(Crowny_Sharp_config))
	@echo "==== Building Crowny-Sharp ($(Crowny_Sharp_config)) ===="
	@${MAKE} --no-print-directory -C Crowny-Sharp -f Makefile config=$(Crowny_Sharp_config)
endif

Crowny-Sandbox: Crowny-Sharp
ifneq (,$(Crowny_Sandbox_config))
	@echo "==== Building Crowny-Sandbox ($(Crowny_Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Crowny-Sandbox -f Makefile config=$(Crowny_Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Crowny/Dependencies/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C Crowny/Dependencies/glad -f Makefile clean
	@${MAKE} --no-print-directory -C Crowny/Dependencies/freetype-gl -f Makefile clean
	@${MAKE} --no-print-directory -C Crowny/Dependencies/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Crowny/Dependencies/freetype2 -f Makefile clean
	@${MAKE} --no-print-directory -C Crowny/Dependencies/assimp -f Makefile clean
	@${MAKE} --no-print-directory -C Crowny -f Makefile clean
	@${MAKE} --no-print-directory -C Crowny-Editor -f Makefile clean
	@${MAKE} --no-print-directory -C Crowny-Sharp -f Makefile clean
	@${MAKE} --no-print-directory -C Crowny-Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_win64"
	@echo "  debug_linux64"
	@echo "  debug_macos64"
	@echo "  debug_web"
	@echo "  release_win64"
	@echo "  release_linux64"
	@echo "  release_macos64"
	@echo "  release_web"
	@echo "  dist_win64"
	@echo "  dist_linux64"
	@echo "  dist_macos64"
	@echo "  dist_web"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glfw"
	@echo "   glad"
	@echo "   freetype-gl"
	@echo "   imgui"
	@echo "   freetype2"
	@echo "   assimp"
	@echo "   Crowny"
	@echo "   Crowny-Editor"
	@echo "   Crowny-Sharp"
	@echo "   Crowny-Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"