<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>GameAssembly</AssemblyName>
    <RootNamespace>GameAssembly</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>disable</Nullable>
    <Deterministic>true</Deterministic>
    <GenerateDependencyFile>true</GenerateDependencyFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Source/**/*.cs" />
    <ProjectReference Include="../Crowny-Sharp/CrownySharp.csproj" />
  </ItemGroup>
</Project>
