#!/usr/bin/env python3
"""Generate Crowny's native and managed input-code contracts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "Scripts" / "input" / "input-codes.json"
KEY_OUTPUT = ROOT / "Crowny" / "Source" / "Crowny" / "Input" / "KeyCodes.h"
MOUSE_OUTPUT = ROOT / "Crowny" / "Source" / "Crowny" / "Input" / "MouseCodes.h"
GAMEPAD_OUTPUT = ROOT / "Crowny" / "Source" / "Crowny" / "Input" / "GamepadCodes.h"
MANAGED_OUTPUT = ROOT / "Crowny-Sharp" / "Source" / "Utils" / "Generated" / "InputCodes.g.cs"


def native_header(alias: str, namespace: str, values: dict[str, int]) -> str:
    members = "\n".join(f"            {name} = {value}," for name, value in values.items())
    return f"""#pragma once
// <auto-generated />

#include <cstdint>

namespace Crowny
{{
    using {alias} = uint32_t;

    namespace {namespace}
    {{
        enum : {alias}
        {{
{members}
        }};
    }} // namespace {namespace}
}} // namespace Crowny
"""


def gamepad_header(buttons: dict[str, int], axes: dict[str, int]) -> str:
    button_members = "\n".join(f"            {name} = {value}," for name, value in buttons.items())
    axis_members = "\n".join(f"            {name} = {value}," for name, value in axes.items())
    return f"""#pragma once
// <auto-generated />

#include <cstdint>

namespace Crowny
{{
    using GamepadButtonCode = uint32_t;
    using GamepadAxisCode = uint32_t;

    namespace GamepadButton
    {{
        enum : GamepadButtonCode
        {{
{button_members}
        }};
    }} // namespace GamepadButton

    namespace GamepadAxis
    {{
        enum : GamepadAxisCode
        {{
{axis_members}
        }};
    }} // namespace GamepadAxis
}} // namespace Crowny
"""


def managed_enum(name: str, values: dict[str, int]) -> str:
    members = "\n".join(f"        {member} = {value}," for member, value in values.items())
    return f"""    public enum {name} : uint
    {{
{members}
    }}
"""


def managed_codes(manifest: dict) -> str:
    mouse_values = dict(manifest["mouseButtons"])
    mouse_values.update(manifest["managedMouseAliases"])
    enums = "\n".join(
        [
            managed_enum("KeyCode", manifest["keys"]),
            managed_enum("MouseCode", mouse_values),
            managed_enum("GamepadButtonCode", manifest["gamepadButtons"]),
            managed_enum("GamepadAxisCode", manifest["gamepadAxes"]),
        ]
    )
    return f"""// <auto-generated />
namespace Crowny
{{
{enums}
}}
"""


def update(path: Path, content: str, check: bool) -> bool:
    content = content.replace("\r\n", "\n")
    existing = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else None
    if existing == content:
        return True
    if check:
        print(f"out of date: {path.relative_to(ROOT)}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"updated: {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    outputs = (
        update(KEY_OUTPUT, native_header("KeyCode", "Key", manifest["keys"]), arguments.check),
        update(MOUSE_OUTPUT, native_header("MouseCode", "Mouse", manifest["mouseButtons"]), arguments.check),
        update(GAMEPAD_OUTPUT, gamepad_header(manifest["gamepadButtons"], manifest["gamepadAxes"]), arguments.check),
        update(MANAGED_OUTPUT, managed_codes(manifest), arguments.check),
    )
    return 0 if all(outputs) else 1


if __name__ == "__main__":
    raise SystemExit(main())
