#pragma once

#include "Crowny/Common/Common.h"

#define CROWNY_VERSION_MAJOR 1
#define CROWNY_VERSION_MINOR 0
#define CROWNY_VERSION_MINEST 0

#define CROWNY_VERSION_STRING_BUILDER(maj, min, mine) CW_STRINGIFY(maj) "." CW_STRINGIFY(min) "." CW_STRINGIFY(mine)

#define CROWNY_VERSION_STRING CROWNY_VERSION_STRING_BUILDER(CROWNY_VERSION_MAJOR, CROWNY_VERSION_MINOR, CROWNY_VERSION_MINEST)