<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <AssemblyName>CrownySharp</AssemblyName>
    <RootNamespace>Crowny</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Deterministic>true</Deterministic>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <DefineConstants>$(DefineConstants);CROWNY_MONO</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Source/**/*.cs" />
    <Compile Include="../Crowny/Dependencies/FastNoiseLite/CSharp/FastNoiseLite.cs" Link="Dependencies/FastNoiseLite.cs" />
  </ItemGroup>
</Project>
