<Project>
  <Import Project="$(MSBuildThisFileDirectory)..\Directory.Build.props" />
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)..\.deps\generated\managed\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory)..\.deps\generated\managed\bin\$(MSBuildProjectName)\</BaseOutputPath>
  </PropertyGroup>
</Project>
