<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Crowny.ManagedHost</AssemblyName>
    <RootNamespace>Crowny.ManagedHost</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <SelfContained>false</SelfContained>
    <RollForward>LatestPatch</RollForward>
    <Deterministic>true</Deterministic>
    <DotNetRuntimeVersion Condition="'$(DotNetRuntimeVersion)' == ''">10.0.0</DotNetRuntimeVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Crowny-Sharp/CrownySharp.csproj" />
    <TrimmerRootDescriptor Include="Generated/ILLink.Descriptors.xml" />
  </ItemGroup>
</Project>
