# Crowny Editor Settings
GridMoveSnap: [0.100000001, 0.100000001, 0.100000001]
GridRotateSnap: 15
GridScaleSnap: 0.100000001
LastOpenProject: C:\dev\Projects\Project1
AutoLoadLastProject: true
ShowImGuiDemo: false
ShowPhysicsColliders2D: false
ShowScriptDebugInfo: false
ShowAssetInfo: false
ShowEmptyMetadataAssetInfo: false
ShowEntityDebugInfo: false
EnableConsoleInfoMessages: true
EnableConsoleWarningMessages: false
EnableConsoleErrorMessages: false
CollapseConsole: true
ScrollToBottom: true
RecentProjects:
  - Path: C:\dev\Projects\Project1
    Timestamp: 1651001207
  - Path: C:\dev\Projects\New Project
    Timestamp: 1648668832
  - Path: C:/dev/Projects\Project4
    Timestamp: 1647607440
  - Path: C:/dev/Projects\Project3
    Timestamp: 1647605544