# Crowny Editor Settings
GridMoveSnap: [0.100000001, 0.100000001, 0.100000001]
GridRotateSnap: 15
GridScaleSnap: 0.100000001
LastOpenProject: C:\dev\Projects\New Project
AutoLoadLastProject: true
ShowImGuiDemo: false
ShowPhysicsColliders2D: false
RecentProjects:
  - Path: C:\dev\Projects\New Project
    Timestamp: 1648645965
  - Path: C:\dev\Projects\Project1
    Timestamp: 1648611247
  - Path: C:/dev/Projects\Project4
    Timestamp: 1647607440
  - Path: C:/dev/Projects\Project3
    Timestamp: 1647605544