#pragma once
// <auto-generated />

#include <stddef.h>
#include <stdint.h>

#if defined(_WIN32)
#define CW_MANAGED_CALL __cdecl
#define CW_MANAGED_EXPORT __declspec(dllexport)
#else
#define CW_MANAGED_CALL
#define CW_MANAGED_EXPORT __attribute__((visibility("default")))
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define CW_MANAGED_ABI_VERSION 3u
#define CW_MANAGED_BOOTSTRAP_TYPE "Crowny.ManagedHost.Bootstrap, Crowny.ManagedHost"
#define CW_MANAGED_BOOTSTRAP_METHOD "GetApi"

typedef int32_t cw_managed_status;
typedef uint64_t cw_managed_instance;

enum cw_managed_status_code
{
    CW_MANAGED_STATUS_OK = 0,
    CW_MANAGED_STATUS_INVALID_ARGUMENT = 1,
    CW_MANAGED_STATUS_ABI_MISMATCH = 2,
    CW_MANAGED_STATUS_NOT_INITIALIZED = 3,
    CW_MANAGED_STATUS_PROGRAM_LOAD_FAILED = 4,
    CW_MANAGED_STATUS_SCRIPT_TYPE_MISSING = 5,
    CW_MANAGED_STATUS_STALE_HANDLE = 6,
    CW_MANAGED_STATUS_MANAGED_EXCEPTION = 7,
    CW_MANAGED_STATUS_BUFFER_WRITE_FAILED = 8,
    CW_MANAGED_STATUS_RELOAD_LEAK = 9,
};

enum cw_managed_event_kind
{
    CW_MANAGED_EVENT_START = 0,
    CW_MANAGED_EVENT_UPDATE = 1,
    CW_MANAGED_EVENT_DESTROY = 2,
    CW_MANAGED_EVENT_COLLISION_ENTER_2_D = 3,
    CW_MANAGED_EVENT_COLLISION_STAY_2_D = 4,
    CW_MANAGED_EVENT_COLLISION_EXIT_2_D = 5,
    CW_MANAGED_EVENT_TRIGGER_ENTER_2_D = 6,
    CW_MANAGED_EVENT_TRIGGER_STAY_2_D = 7,
    CW_MANAGED_EVENT_TRIGGER_EXIT_2_D = 8,
    CW_MANAGED_EVENT_COLLISION_ENTER_3_D = 9,
    CW_MANAGED_EVENT_COLLISION_STAY_3_D = 10,
    CW_MANAGED_EVENT_COLLISION_EXIT_3_D = 11,
    CW_MANAGED_EVENT_TRIGGER_ENTER_3_D = 12,
    CW_MANAGED_EVENT_TRIGGER_STAY_3_D = 13,
    CW_MANAGED_EVENT_TRIGGER_EXIT_3_D = 14,
};

enum cw_managed_host_binding
{
    CW_MANAGED_BINDING_ENTITY_HAS_COMPONENT = 1,
    CW_MANAGED_BINDING_ENTITY_ADD_COMPONENT = 2,
    CW_MANAGED_BINDING_ENTITY_REMOVE_COMPONENT = 3,
    CW_MANAGED_BINDING_TRANSFORM_GET_POSITION = 10,
    CW_MANAGED_BINDING_TRANSFORM_SET_POSITION = 11,
    CW_MANAGED_BINDING_TRANSFORM_GET_LOCAL_POSITION = 12,
    CW_MANAGED_BINDING_TRANSFORM_SET_LOCAL_POSITION = 13,
    CW_MANAGED_BINDING_TRANSFORM_GET_SCALE = 14,
    CW_MANAGED_BINDING_TRANSFORM_SET_SCALE = 15,
    CW_MANAGED_BINDING_TRANSFORM_GET_LOCAL_SCALE = 16,
    CW_MANAGED_BINDING_TRANSFORM_SET_LOCAL_SCALE = 17,
    CW_MANAGED_BINDING_TRANSFORM_GET_ROTATION = 18,
    CW_MANAGED_BINDING_TRANSFORM_SET_ROTATION = 19,
    CW_MANAGED_BINDING_TRANSFORM_GET_LOCAL_ROTATION = 20,
    CW_MANAGED_BINDING_TRANSFORM_SET_LOCAL_ROTATION = 21,
    CW_MANAGED_BINDING_TRANSFORM_GET_LOCAL_TO_WORLD_MATRIX = 22,
    CW_MANAGED_BINDING_TRANSFORM_GET_WORLD_TO_LOCAL_MATRIX = 23,
    CW_MANAGED_BINDING_TRANSFORM_GET_EULER_ANGLES = 24,
    CW_MANAGED_BINDING_TRANSFORM_SET_EULER_ANGLES = 25,
    CW_MANAGED_BINDING_TRANSFORM_GET_LOCAL_EULER_ANGLES = 26,
    CW_MANAGED_BINDING_TRANSFORM_SET_LOCAL_EULER_ANGLES = 27,
    CW_MANAGED_BINDING_INPUT_GET_KEY = 30,
    CW_MANAGED_BINDING_INPUT_GET_KEY_DOWN = 31,
    CW_MANAGED_BINDING_INPUT_GET_KEY_UP = 32,
    CW_MANAGED_BINDING_INPUT_GET_MOUSE_BUTTON = 33,
    CW_MANAGED_BINDING_INPUT_GET_MOUSE_BUTTON_DOWN = 34,
    CW_MANAGED_BINDING_INPUT_GET_MOUSE_BUTTON_UP = 35,
    CW_MANAGED_BINDING_INPUT_GET_MOUSE_SCROLL_X = 36,
    CW_MANAGED_BINDING_INPUT_GET_MOUSE_SCROLL_Y = 37,
    CW_MANAGED_BINDING_INPUT_GET_MOUSE_POSITION = 38,
    CW_MANAGED_BINDING_TIME_GET_TIME = 40,
    CW_MANAGED_BINDING_TIME_GET_FIXED_DELTA_TIME = 41,
    CW_MANAGED_BINDING_TIME_GET_SMOOTH_DELTA_TIME = 42,
    CW_MANAGED_BINDING_TIME_GET_REALTIME_SINCE_STARTUP = 43,
    CW_MANAGED_BINDING_TIME_GET_FRAME_COUNT = 44,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_MASS = 50,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_MASS = 51,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_BODY_TYPE = 52,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_BODY_TYPE = 53,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_SLEEP_MODE = 54,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_SLEEP_MODE = 55,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_COLLISION_DETECTION_MODE = 56,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_COLLISION_DETECTION_MODE = 57,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_INTERPOLATION = 58,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_INTERPOLATION = 59,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_AUTO_MASS = 60,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_AUTO_MASS = 61,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_LAYER = 62,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_LAYER = 63,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_LINEAR_DRAG = 64,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_LINEAR_DRAG = 65,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_ANGULAR_DRAG = 66,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_ANGULAR_DRAG = 67,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_GRAVITY_SCALE = 68,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_GRAVITY_SCALE = 69,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_CENTER_OF_MASS = 70,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_CENTER_OF_MASS = 71,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_INERTIA = 72,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_INERTIA = 73,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_CONSTRAINTS = 74,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_CONSTRAINTS = 75,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_ROTATION = 76,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_POSITION = 77,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_LINEAR_VELOCITY = 78,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_LINEAR_VELOCITY = 79,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_ANGULAR_VELOCITY = 80,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_ANGULAR_VELOCITY = 81,
    CW_MANAGED_BINDING_RIGIDBODY_2_DGET_AWAKE = 82,
    CW_MANAGED_BINDING_RIGIDBODY_2_DSET_AWAKE = 83,
    CW_MANAGED_BINDING_RIGIDBODY_2_DADD_FORCE = 84,
    CW_MANAGED_BINDING_RIGIDBODY_2_DADD_FORCE_AT_POSITION = 85,
    CW_MANAGED_BINDING_RIGIDBODY_2_DADD_TORQUE = 86,
    CW_MANAGED_BINDING_AUDIO_SOURCE_GET_VOLUME = 100,
    CW_MANAGED_BINDING_AUDIO_SOURCE_SET_VOLUME = 101,
    CW_MANAGED_BINDING_AUDIO_SOURCE_GET_PITCH = 102,
    CW_MANAGED_BINDING_AUDIO_SOURCE_SET_PITCH = 103,
    CW_MANAGED_BINDING_AUDIO_SOURCE_GET_MIN_DISTANCE = 104,
    CW_MANAGED_BINDING_AUDIO_SOURCE_SET_MIN_DISTANCE = 105,
    CW_MANAGED_BINDING_AUDIO_SOURCE_GET_MAX_DISTANCE = 106,
    CW_MANAGED_BINDING_AUDIO_SOURCE_SET_MAX_DISTANCE = 107,
    CW_MANAGED_BINDING_AUDIO_SOURCE_GET_LOOP = 108,
    CW_MANAGED_BINDING_AUDIO_SOURCE_SET_LOOP = 109,
    CW_MANAGED_BINDING_AUDIO_SOURCE_GET_MUTED = 110,
    CW_MANAGED_BINDING_AUDIO_SOURCE_SET_MUTED = 111,
    CW_MANAGED_BINDING_AUDIO_SOURCE_GET_PLAY_ON_AWAKE = 112,
    CW_MANAGED_BINDING_AUDIO_SOURCE_SET_PLAY_ON_AWAKE = 113,
    CW_MANAGED_BINDING_AUDIO_SOURCE_GET_TIME = 114,
    CW_MANAGED_BINDING_AUDIO_SOURCE_SET_TIME = 115,
    CW_MANAGED_BINDING_AUDIO_SOURCE_GET_CLIP = 116,
    CW_MANAGED_BINDING_AUDIO_SOURCE_SET_CLIP = 117,
    CW_MANAGED_BINDING_AUDIO_SOURCE_GET_STATE = 118,
    CW_MANAGED_BINDING_AUDIO_SOURCE_PLAY = 119,
    CW_MANAGED_BINDING_AUDIO_SOURCE_PAUSE = 120,
    CW_MANAGED_BINDING_AUDIO_SOURCE_STOP = 121,
};

typedef struct cw_managed_string_view
{
    const uint8_t* data;
    uint32_t length;
} cw_managed_string_view;

typedef struct cw_managed_blob
{
    const uint8_t* data;
    uint64_t length;
} cw_managed_blob;

typedef struct cw_managed_uuid
{
    uint8_t bytes[16];
} cw_managed_uuid;

typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_write_blob_fn)(void* context, const uint8_t* data, uint64_t length);

typedef struct cw_managed_blob_writer
{
    uint32_t size;
    void* context;
    cw_managed_write_blob_fn write;
} cw_managed_blob_writer;

typedef struct cw_managed_contact_point
{
    float position[3];
    float normal[3];
    float separation;
    float impulse;
} cw_managed_contact_point;

typedef struct cw_managed_event
{
    uint32_t size;
    uint32_t kind;
    float delta_time;
    cw_managed_uuid other_entity;
    float relative_velocity[3];
    cw_managed_blob payload; /* Packed cw_managed_contact_point values. */
} cw_managed_event;

typedef void(CW_MANAGED_CALL* cw_managed_log_fn)(void* context, uint32_t severity, cw_managed_string_view code,
                                                 cw_managed_string_view message, cw_managed_string_view stack);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_get_entity_name_fn)(void* context, cw_managed_uuid entity,
                                                                         cw_managed_string_view* name);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_set_entity_name_fn)(void* context, cw_managed_uuid entity,
                                                                         cw_managed_string_view name);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_find_entity_by_name_fn)(void* context, cw_managed_string_view name,
                                                                             cw_managed_uuid* entity);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_get_entity_parent_fn)(void* context, cw_managed_uuid entity,
                                                                           cw_managed_uuid* parent);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_set_entity_parent_fn)(void* context, cw_managed_uuid entity,
                                                                           cw_managed_uuid parent);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_destroy_entity_fn)(void* context, cw_managed_uuid entity);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_invoke_host_binding_fn)(void* context, uint32_t binding,
                                                                             cw_managed_uuid entity, cw_managed_blob input,
                                                                             cw_managed_blob* output);

typedef struct cw_managed_host_api
{
    uint32_t size;
    uint32_t abi_version;
    void* context;
    cw_managed_log_fn log;
    cw_managed_get_entity_name_fn get_entity_name;
    cw_managed_set_entity_name_fn set_entity_name;
    cw_managed_find_entity_by_name_fn find_entity_by_name;
    cw_managed_get_entity_parent_fn get_entity_parent;
    cw_managed_set_entity_parent_fn set_entity_parent;
    cw_managed_destroy_entity_fn destroy_entity;
    cw_managed_invoke_host_binding_fn invoke_host_binding;
} cw_managed_host_api;

typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_initialize_fn)(const cw_managed_host_api* host);
typedef void(CW_MANAGED_CALL* cw_managed_shutdown_fn)(void);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_load_program_fn)(cw_managed_string_view assembly_path, uint64_t generation);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_unload_program_fn)(void);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_get_catalog_fn)(cw_managed_blob_writer* output);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_create_script_fn)(cw_managed_string_view assembly_name,
                                                                       cw_managed_string_view type_namespace,
                                                                       cw_managed_string_view type_name,
                                                                       cw_managed_uuid entity, cw_managed_blob initial_state,
                                                                       cw_managed_instance* instance);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_destroy_script_fn)(cw_managed_instance instance);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_dispatch_fn)(cw_managed_instance instance,
                                                                  const cw_managed_event* event_data);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_capture_state_fn)(cw_managed_instance instance,
                                                                       cw_managed_blob_writer* output);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_apply_state_fn)(cw_managed_instance instance, cw_managed_blob state);
typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_collect_diagnostics_fn)(cw_managed_blob_writer* output);

typedef struct cw_managed_program_api
{
    uint32_t size;
    uint32_t abi_version;
    cw_managed_initialize_fn initialize;
    cw_managed_shutdown_fn shutdown;
    cw_managed_load_program_fn load_program;
    cw_managed_unload_program_fn unload_program;
    cw_managed_get_catalog_fn get_catalog;
    cw_managed_create_script_fn create_script;
    cw_managed_destroy_script_fn destroy_script;
    cw_managed_dispatch_fn dispatch;
    cw_managed_capture_state_fn capture_state;
    cw_managed_apply_state_fn apply_state;
    cw_managed_collect_diagnostics_fn collect_diagnostics;
} cw_managed_program_api;

typedef cw_managed_status(CW_MANAGED_CALL* cw_managed_get_api_fn)(cw_managed_program_api* api, uint32_t api_size);

#ifdef __cplusplus
}

static_assert(sizeof(cw_managed_uuid) == 16, "Managed UUID ABI layout changed.");
static_assert(sizeof(cw_managed_contact_point) == 32, "Managed contact ABI layout changed.");
#endif
